Ignore rule 'generator-star-spacing' because causing node_modules error
... terminal error log:

```
khoaphan@Khoas-MacBook-Pro:~/Desktop/backbone$ git push origin forgot-password

> backbone@0.0.1 prepush /Users/khoaphan/Desktop/backbone
> npm run lint

> backbone@0.0.1 lint /Users/khoaphan/Desktop/backbone
> eslint index.* app/**

The react/require-extension rule is deprecated. Please use the import/extensions rule from eslint-plugin-import instead.
Cannot read property 'value' of undefined
TypeError: Cannot read property 'value' of undefined
    at getStarToken (/Users/khoaphan/Desktop/backbone/node_modules/eslint/lib/rules/generator-star-spacing.js:68:25)
    at EventEmitter.checkFunction (/Users/khoaphan/Desktop/backbone/node_modules/eslint/lib/rules/generator-star-spacing.js:128:29)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode (/Users/khoaphan/Desktop/backbone/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/Users/khoaphan/Desktop/backbone/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (/Users/khoaphan/Desktop/backbone/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.enter (/Users/khoaphan/Desktop/backbone/node_modules/eslint/lib/eslint.js:898:36)
    at Controller.__execute (/Users/khoaphan/Desktop/backbone/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/khoaphan/Desktop/backbone/node_modules/eslint/node_modules/estraverse/estraverse.js:501:28)
```